unsetopt AUTO_CD

setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt EXTENDED_HISTORY

setopt COMPLETE_IN_WORD
setopt ALWAYS_TO_END

setopt PROMPT_SUBST

unsetopt MENU_COMPLETE
setopt AUTO_MENU
setopt histignorealldups
setopt histignorespace
setopt histsavenodups
